# Generated by Django 4.1 on 2022-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=6)),
                ("event", models.CharField(max_length=4)),
                ("hours", models.CharField(max_length=20)),
                ("kilometers", models.CharField(max_length=20)),
                ("top_effort", models.CharField(max_length=20)),
                ("top", models.BooleanField(default=False)),
            ],
        ),
    ]
