# Generated by Django 4.1 on 2022-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="top",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="kilometers",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="top_effort",
            field=models.CharField(max_length=20),
        ),
    ]
